// <auto-generated />
using EFconASPyMVC.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFconASPyMVC.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFconASPyMVC.Models.Hermandad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cif")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaFundacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hermandad");
                });

            modelBuilder.Entity("EFconASPyMVC.Models.Hermano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaNacimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HermandadId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HermandadId");

                    b.ToTable("Hermano");
                });

            modelBuilder.Entity("EFconASPyMVC.Models.Puesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombrePuesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Puesto");
                });

            modelBuilder.Entity("EFconASPyMVC.Models.PuestoHermano", b =>
                {
                    b.Property<int>("PuestoId")
                        .HasColumnType("int");

                    b.Property<int>("HermanoId")
                        .HasColumnType("int");

                    b.Property<string>("FechaFin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaInicio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PuestoId", "HermanoId");

                    b.HasIndex("HermanoId");

                    b.ToTable("PuestoHermano");
                });

            modelBuilder.Entity("EFconASPyMVC.Models.Tunica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("FechaEntrega")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HermanoId")
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Talla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HermanoId")
                        .IsUnique();

                    b.ToTable("Tunica");
                });

            modelBuilder.Entity("EFconASPyMVC.Models.Hermano", b =>
                {
                    b.HasOne("EFconASPyMVC.Models.Hermandad", "Hermandad")
                        .WithMany("Hermanos")
                        .HasForeignKey("HermandadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hermandad");
                });

            modelBuilder.Entity("EFconASPyMVC.Models.PuestoHermano", b =>
                {
                    b.HasOne("EFconASPyMVC.Models.Hermano", "Hermano")
                        .WithMany("PuestosHermanos")
                        .HasForeignKey("HermanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFconASPyMVC.Models.Puesto", "Puesto")
                        .WithMany("PuestosHermanos")
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hermano");

                    b.Navigation("Puesto");
                });

            modelBuilder.Entity("EFconASPyMVC.Models.Tunica", b =>
                {
                    b.HasOne("EFconASPyMVC.Models.Hermano", "Hermano")
                        .WithOne("Tunica")
                        .HasForeignKey("EFconASPyMVC.Models.Tunica", "HermanoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hermano");
                });

            modelBuilder.Entity("EFconASPyMVC.Models.Hermandad", b =>
                {
                    b.Navigation("Hermanos");
                });

            modelBuilder.Entity("EFconASPyMVC.Models.Hermano", b =>
                {
                    b.Navigation("PuestosHermanos");

                    b.Navigation("Tunica")
                        .IsRequired();
                });

            modelBuilder.Entity("EFconASPyMVC.Models.Puesto", b =>
                {
                    b.Navigation("PuestosHermanos");
                });
#pragma warning restore 612, 618
        }
    }
}
